run_tests: do not -I the build/include directory to fix tests on Linux / clang-16
test016, test027 and test031 fail on Debian/Linux with LLVM 16 when
interacting with the cstdint and memory headers.

The errors look like this:

    test016
    # ./build/bbl/bbl-translate test/test016.cpp -- --std=c++17 -Ibbl/include -Ibuild/include -- test016 -o build/test/out
    test/test016.cpp:7:17: error: unknown type name 'int64_t'
    enum class Bar: int64_t {
                ^
    [error] [api_cpp_context.cpp:45] bbl/src/cpp_context.cpp:2603 compilation generated 1 errors. Cannot continue

    test027
    # ./build/bbl/bbl-translate test/test027.cpp -- --std=c++17 -Ibbl/include -Ibuild/include -- test027 -o build/test/out
    In file included from test/test027.cpp:3:
    In file included from /usr/lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/memory:74:
    /usr/lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/bits/align.h:66:42:
    error: unknown type name 'uintptr_t'
    const auto __intptr = reinterpret_cast<uintptr_t>(__ptr);
                                            ^
    /usr/lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/bits/align.h:67:36:
    error: arithmetic on a pointer to void
    const auto __aligned = (__intptr - 1u + __align) & -__align;
                            ~~~~~~~~ ^
    [error] [api_cpp_context.cpp:45] bbl/src/cpp_context.cpp:2603 compilation generated 2 errors. Cannot continue

The errors are caused by the `-Ibuild/include` include path entry, which
causes the system headers to run into errors when interacting with the
stdint types.

Removing this entry gets the test suite passing.